### ISSUE TITLE
Missing module

### ISSUE THREAD

**Issue by Furqankhanzada** [demandcluster/opencommerce-admin#2]
I am having trouble running this project.  below are the issue:

``` ERR_PNPM_NO_MATCHING_VERSION_INSIDE_WORKSPACE  In apps/admin: No matching version found for @demandcluster/core-ui@* inside the workspace```

<img width="449" alt="image" src="https://user-images.githubusercontent.com/2400215/188915847-2e83b78f-5520-4760-92fa-19b98aac09aa.png">

unable to access these 2 modules:

[demandcluster-core-ui @ eb68e59](https://github.com/demandcluster/demandcluster-core-ui/tree/eb68e59d8ce3fc475ef37b08d2e423754e1ccedb)
[demandcluster-merchant-ui @ 3e1f399](https://github.com/demandcluster/demandcluster-merchant-ui/tree/3e1f3992e9cf70d575f1d2cf4cab0cc08d79c90a)

<img width="856" alt="image" src="https://user-images.githubusercontent.com/2400215/188916662-f1338a5f-f36d-45be-9470-5d336d013960.png">

**Comment by tedraykov** [comment]
This admin is originally planned to include custom UI for the Demandcluster platform. If you want to use only the core MOC features, you must remove the git submodules that are linked to the private demandcluster UI modules.

**Comment by Furqankhanzada** [comment]
Removed these lines from mentioned files and it worked.

https://github.com/demandcluster/opencommerce-admin/blob/5f1a631a1460ebfb7d0988ee93b84cac287e3b9c/apps/admin/package.json#L13-L14 

https://github.com/demandcluster/opencommerce-admin/blob/5f1a631a1460ebfb7d0988ee93b84cac287e3b9c/apps/admin/src/util/prepareRoutes.ts#L3-L4

Also renamed `.env.example` to `.env` and set variables also add missing var `VITE_PUBLIC_REST_API_URL` to make it work.

Hope that helps other who want to run the project 👍🏼
